# Generated by Django 3.0.3 on 2020-02-13 10:20

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('image_id', models.CharField(max_length=100, unique=True, verbose_name='상품 이미지 id')),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('all', 'all')], max_length=6, verbose_name='성별')),
                ('category', models.CharField(choices=[('skincare', 'skincare'), ('maskpack', 'maskpack'), ('suncare', 'suncare'), ('basemakeup', 'basemakeup')], max_length=10, verbose_name='카테고리')),
                ('ingredient', models.TextField(verbose_name='구성 성분 이름')),
                ('monthly_sales', models.PositiveIntegerField(default=0, verbose_name='이번달 판매 수량')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
