# Generated by Django 3.0.3 on 2020-02-14 04:23

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('birdview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='성분명')),
                ('oily', models.CharField(choices=[('O', 'beneficial'), ('X', 'harmful'), ('', 'no effect')], max_length=1, verbose_name='지성 영향')),
                ('dry', models.CharField(choices=[('O', 'beneficial'), ('X', 'harmful'), ('', 'no effect')], max_length=1, verbose_name='건성 영향')),
                ('sensitive', models.CharField(choices=[('O', 'beneficial'), ('X', 'harmful'), ('', 'no effect')], max_length=1, verbose_name='민감성 영향')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='item',
            name='ingredient_set',
            field=models.ManyToManyField(related_name='items', to='birdview.Ingredient'),
        ),
    ]
