# Generated by Django 3.0.3 on 2020-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdview', '0002_auto_20200214_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredient_score_dry',
            field=models.IntegerField(default=0, verbose_name='지성 피부 성분 점수'),
        ),
        migrations.AddField(
            model_name='item',
            name='ingredient_score_oily',
            field=models.IntegerField(default=0, verbose_name='지성 피부 성분 점수'),
        ),
        migrations.AddField(
            model_name='item',
            name='ingredient_score_sensitive',
            field=models.IntegerField(default=0, verbose_name='지성 피부 성분 점수'),
        ),
    ]
